import type { GameItem, Machine, ShopInfo } from "../types";

export const VALID_SETUP_CODE = "WB-SHOP-4821";

export const shop: ShopInfo = {
  name: "Windhoek Central",
  location: "Independence Ave, Windhoek",
  tagline: "Independent. Fair. Reliable. Windhoek Central.",
};

export const machineConfig: { smartPc: Machine; terminal: Machine } = {
  smartPc: {
    name: "Smart PC-03",
    type: "smart-pc",
    balance: 250.00,
    shopName: shop.name,
    location: shop.location,
    action: "Cash Out",
  },
  terminal: {
    name: "Terminal-02",
    type: "terminal",
    balance: 100.00,
    shopName: shop.name,
    location: shop.location,
    action: "Print Cashout Ticket",
  },
};

export const games: GameItem[] = [
  {
    id: 1,
    name: "aviator",
    title: "AVIATOR",
    subtitle: "FLY HIGH • 10,000X MAX",
    category: "crash",
    categories: ["crash", "instant", "spribe"],
    theme: "theme-red",
    badge: { text: "HOT", type: "hot", icon: "fa-solid fa-fire" },
    image: "/assets/games/SPRIBE/AVIATOR.png",
    actionText: "PLAY NOW",
  },
  {
    id: 2,
    name: "dice",
    title: "DICE",
    subtitle: "ROLL & WIN • 98.6% RTP",
    category: "table",
    categories: ["table", "instant", "spribe"],
    theme: "theme-purple",
    badge: { text: "TOP", type: "cyan", icon: "fa-solid fa-dice" },
    image: "/assets/games/SPRIBE/DICE.png",
    actionText: "ROLL NOW",
  },
  {
    id: 3,
    name: "plinko",
    title: "PLINKO",
    subtitle: "DROP BALL • 1,000X MULTI",
    category: "instant",
    categories: ["instant", "spribe"],
    theme: "theme-magenta",
    badge: { text: "HOT", type: "hot", icon: "fa-solid fa-bullseye" },
    image: "/assets/games/SPRIBE/PLINKO.png",
    actionText: "DROP NOW",
  },
  {
    id: 4,
    name: "mines",
    title: "MINES",
    subtitle: "AVOID MINES • CASH OUT",
    category: "table",
    categories: ["instant", "table", "spribe"],
    theme: "theme-green",
    badge: { text: "VIP", type: "green", icon: "fa-solid fa-shield-halved" },
    image: "/assets/games/SPRIBE/MINES.png",
    actionText: "PLAY NOW",
  },
  {
    id: 5,
    name: "soccer",
    title: "GOAL / SOCCER",
    subtitle: "SCORE BIG • 97.8% RTP",
    category: "sports",
    categories: ["sports", "spribe", "instant"],
    theme: "theme-blue",
    badge: { text: "POPULAR", type: "cyan", icon: "fa-solid fa-futbol" },
    image: "/assets/games/SPRIBE/SOCCER.png",
    actionText: "KICK NOW",
  },
  {
    id: 6,
    name: "balloon",
    title: "BALLOON",
    subtitle: "DON'T LET IT POP",
    category: "crash",
    categories: ["crash", "instant", "spribe"],
    theme: "theme-gold",
    badge: { text: "FUN", type: "gold", icon: "fa-solid fa-wind" },
    image: "/assets/games/SPRIBE/BALLON.png",
    actionText: "INFLATE NOW",
  },
  {
    id: 7,
    name: "hilo",
    title: "HILO",
    subtitle: "GUESS NEXT CARD",
    category: "table",
    categories: ["table", "spribe", "instant"],
    theme: "theme-blue",
    badge: { text: "NEW", type: "cyan", icon: "fa-solid fa-diamond" },
    image: "/assets/games/SPRIBE/HILO.png",
    actionText: "PLAY NOW",
  },
  {
    id: 8,
    name: "hotline",
    title: "HOTLINE",
    subtitle: "FAST ACTION • INSTANT WIN",
    category: "instant",
    categories: ["instant", "spribe"],
    theme: "theme-red",
    badge: { text: "HOT", type: "hot", icon: "fa-solid fa-fire" },
    image: "/assets/games/SPRIBE/HOTLINE.png",
    actionText: "PLAY NOW",
  },
  {
    id: 9,
    name: "keno",
    title: "KENO",
    subtitle: "CLASSIC LOTTERY DRAW",
    category: "table",
    categories: ["table", "spribe"],
    theme: "theme-purple",
    badge: { text: "CLASSIC", type: "cyan", icon: "fa-solid fa-list-ol" },
    image: "/assets/games/SPRIBE/KENO.png",
    actionText: "PLAY NOW",
  },
  {
    id: 10,
    name: "keno80",
    title: "KENO 80",
    subtitle: "80 BALLS • BIG WINS",
    category: "table",
    categories: ["table", "spribe"],
    theme: "theme-magenta",
    badge: { text: "VIP", type: "green", icon: "fa-solid fa-gem" },
    image: "/assets/games/SPRIBE/KENO80.png",
    actionText: "PLAY NOW",
  },
  {
    id: 11,
    name: "miniroulette",
    title: "MINI ROULETTE",
    subtitle: "QUICK SPINS • 12 NUMBERS",
    category: "table",
    categories: ["table", "spribe"],
    theme: "theme-blue",
    badge: { text: "HOT", type: "hot", icon: "fa-solid fa-circle" },
    image: "/assets/games/SPRIBE/MINIROULETTE.png",
    actionText: "SPIN NOW",
  },
  {
    id: 12,
    name: "pilot",
    title: "PILOT",
    subtitle: "FLYING HIGH • CASH OUT",
    category: "crash",
    categories: ["crash", "spribe"],
    theme: "theme-red",
    badge: { text: "FUN", type: "hot", icon: "fa-solid fa-plane" },
    image: "/assets/games/SPRIBE/PILOT.png",
    actionText: "FLY NOW",
  },
  {
    id: 13,
    name: "trader",
    title: "TRADER",
    subtitle: "MARKET CHART • CASH OUT",
    category: "crash",
    categories: ["crash", "spribe"],
    theme: "theme-green",
    badge: { text: "NEW", type: "cyan", icon: "fa-solid fa-chart-line" },
    image: "/assets/games/SPRIBE/TRADER.png",
    actionText: "TRADE NOW",
  },
  {
    id: 14,
    name: "gates of olympus",
    title: "OLYMPUS BLITZ",
    subtitle: "GATES OF ZEUS • 5,000X",
    category: "slots",
    categories: ["slots"],
    theme: "theme-gold",
    badge: { text: "500X", type: "gold", icon: "fa-solid fa-bolt" },
    image: "/assets/games/3.png",
    actionText: "SPIN NOW",
  },
  {
    id: 15,
    name: "sweet bonanza",
    title: "SWEET BONANZA",
    subtitle: "TUMBLE REELS • 100X MULTI",
    category: "slots",
    categories: ["slots"],
    theme: "theme-magenta",
    badge: { text: "BONUS", type: "hot", icon: "fa-solid fa-fire" },
    image: "/assets/games/2.png",
    actionText: "SPIN NOW",
  },
  {
    id: 11,
    name: "sugar rush",
    title: "SUGAR RUSH",
    subtitle: "MULTIPLIER SPOTS • 128X",
    category: "slots",
    categories: ["slots", "instant"],
    theme: "theme-purple",
    badge: { text: "NEW", type: "cyan", icon: "fa-solid fa-star" },
    image: "/assets/games/4.png",
    actionText: "SPIN NOW",
  },
  {
    id: 12,
    name: "live roulette",
    title: "LIVE ROULETTE",
    subtitle: "EUROPEAN • 36 NUMBERS",
    category: "live",
    categories: ["table", "live"],
    theme: "theme-red",
    badge: { text: "LIVE", type: "live", icon: "fa-solid fa-circle" },
    image: "/assets/games/5.png",
    actionText: "BET NOW",
  },
  {
    id: 13,
    name: "blackjack pro",
    title: "BLACKJACK PRO",
    subtitle: "PERFECT PAIRS • 3:2 PAY",
    category: "table",
    categories: ["table", "live"],
    theme: "theme-green",
    badge: { text: "VIP", type: "green", icon: "fa-solid fa-shield-halved" },
    image: "/assets/games/6.png",
    actionText: "DEAL NOW",
  },
  {
    id: 14,
    name: "live baccarat",
    title: "LIVE BACCARAT",
    subtitle: "SPEED BACCARAT • NO COMM",
    category: "live",
    categories: ["table", "live"],
    theme: "theme-purple",
    badge: { text: "LIVE", type: "cyan", icon: "fa-solid fa-user-tie" },
    image: "/assets/games/2.png",
    actionText: "BET NOW",
  },
  {
    id: 15,
    name: "virtual sports",
    title: "VIRTUAL LEAGUE",
    subtitle: "3-MIN MATCHES • LIVE ODDS",
    category: "sports",
    categories: ["sports"],
    theme: "theme-blue",
    badge: { text: "24/7", type: "cyan", icon: "fa-solid fa-futbol" },
    image: "/assets/games/5.png",
    actionText: "BET NOW",
  },
  {
    id: 16,
    name: "crash royale",
    title: "CRASH ROYALE",
    subtitle: "118.5K PLAYERS • ROOM",
    category: "crash",
    categories: ["crash", "live"],
    theme: "theme-red",
    badge: { text: "24/7", type: "hot", icon: "fa-solid fa-fire" },
    image: "/assets/games/1.png",
    actionText: "JOIN ROOM",
  },
];
